# Generated by Django 4.0.6 on 2022-08-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeckillCampaign",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("campaign_name", models.CharField(max_length=200)),
                ("seckill_price", models.IntegerField(default=0)),
                ("campaign_status", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("total_stock", models.IntegerField(default=0)),
                ("available_stock", models.IntegerField(default=0)),
                ("lock_stock", models.IntegerField(default=0)),
            ],
        ),
    ]
