# Generated by Django 4.0.6 on 2022-08-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seckill", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seckillcampaign",
            options={"verbose_name_plural": "seckill_campaign"},
        ),
    ]
