# Generated by Django 4.0.6 on 2022-08-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seckill", "0002_alter_seckillcampaign_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seckillcampaign",
            options={},
        ),
        migrations.AddField(
            model_name="seckillcampaign",
            name="original_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="seckillcampaign",
            table="seckill_campaign",
        ),
    ]
