# Generated by Django 4.0.6 on 2022-08-02 03:18

from django.db import migrations
from ..models import Commodity


def add_new_commodities(apps, scehma_editor):
    commodity1 = Commodity(
        commodity_name="MacBook 13",
        commodity_description="The 13 version of Macbook",
        commodity_price=124000,
    )
    commodity2 = Commodity(
        commodity_name="MacBook 14",
        commodity_description="The 14 version of Macbook",
        commodity_price=134000,
    )
    commodity1.save()
    commodity2.save()


class Migration(migrations.Migration):

    dependencies = [
        ("seckill", "0004_commodity_seckillcampaign_commodity"),
    ]

    operations = [migrations.RunPython(add_new_commodities)]
